# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6e7ad54dcd62a6d4bd2b6751879596503514c18dcfad17b21cda6c68c583f3559f7770380c9345907fe6c477deb0ad50bad92f271a94beaffe101e0ec431ac3

test:
  secret_key_base: ba29a631b1eb284c4f1b8fdf455ca47b28977921293644828278264654f83d751e30c4a0f3397d854c233d26ec357459fc4f858bbccc7778afc99a2505fde4aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
